import Foundation

struct SavedArticle: Codable, Identifiable {
    var id: UUID?             // Auto-generated by Postgres upon insertion
    let user_id: UUID
    let article_title: String
    let article_description: String?  // Summary / description of the article
    let image_url: String?
    let article_url: String

    // Custom decoder so rows that pre-date the article_description column
    // (where the key is absent from the JSON) don't throw a decode error.
    enum CodingKeys: String, CodingKey {
        case id, user_id, article_title, article_description, image_url, article_url
    }

    init(id: UUID? = nil, user_id: UUID, article_title: String,
         article_description: String?, image_url: String?, article_url: String) {
        self.id = id
        self.user_id = user_id
        self.article_title = article_title
        self.article_description = article_description
        self.image_url = image_url
        self.article_url = article_url
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id                  = try c.decodeIfPresent(UUID.self,   forKey: .id)
        user_id             = try c.decode(UUID.self,            forKey: .user_id)
        article_title       = try c.decode(String.self,          forKey: .article_title)
        article_description = try c.decodeIfPresent(String.self, forKey: .article_description)
        image_url           = try c.decodeIfPresent(String.self, forKey: .image_url)
        article_url         = try c.decode(String.self,          forKey: .article_url)
    }

    /// Maps a saved row back into an Article so existing views work without changes.
    var asArticle: Article {
        Article(
            id: article_url,
            title: article_title,
            description: article_description,   // ← now populated
            image: image_url,
            url: article_url
        )
    }
}
